apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver1
  template:
    metadata:
      labels:
        app: webserver1
    spec:
      containers:
      - name: webserver1
        image: webserver1:latest
